[package]
name = "hc-vault-help"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
once_cell = "1.19.0"
toml = "0.8.19"
vaultrs = "0.7.2"
serde = { version = "1.0.205", features = ["derive"] }
env_logger = "0.11.5"